### ISSUE TITLE
[오탈자제보] P141(06-2 스택의 정의)

### ISSUE THREAD

**Issue by codevilot** [kciter/coding-interview-js#1]
Before
만약 top이 0이면 데이터가 1개 있는 것이므로 초기값을 0이 아니라 -1로 했음에 주목하세요

After
만약 top이 0이면 데이터가 1개 있는 것이므로 초기값을 -1이 아니라 0로 했음에 주목하세요

다음과 같이 수정하는게 맞는 것 같습니다.

**Comment by kciter** [comment]
확인했습니다. 제보주셔서 감사합니다!

**Comment by kciter** [comment]
@codevilot 
안녕하세요. 지금 다시 확인해보니 해당 내용은 정상입니다. 
`top`이 -1인 경우 아무 데이터도 추가가 되지 않은 상태입니다. 여기서 `top`이 0이 된 경우엔 데이터가 하나 추가된 것으로 간주하기 때문에 **-1이 아무것도 없는 상태**입니다. 따라서 책 내용에선 초기값을 -1로 하는 것이 정상입니다. 

다만 이후 구현 파트와 조금 상이해서 혼란이 있을 수는 있을 것 같습니다. 다음에 가능하다면 수정조치 하도록 하겠습니다.

감사합니다. 😊
